// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddCategory 添加新分类
 * @param {string} categoryName
 * @returns {$CancellablePromise<void>}
 */
export function AddCategory(categoryName) {
    return $Call.ByID(1180544068, categoryName);
}

/**
 * AddTool 添加新工具
 * @param {$models.Tool} tool
 * @param {string} categoryName
 * @returns {$CancellablePromise<void>}
 */
export function AddTool(tool, categoryName) {
    return $Call.ByID(1841764470, tool, categoryName);
}

/**
 * AutoAddScannedTools 自动添加扫描到的工具
 * @param {$models.ScannedTool[]} tools
 * @returns {$CancellablePromise<void>}
 */
export function AutoAddScannedTools(tools) {
    return $Call.ByID(360282066, tools);
}

/**
 * BrowseDirectory 浏览指定目录（支持相对路径和绝对路径）
 * @param {string} pathInput
 * @returns {$CancellablePromise<$models.FileInfo[]>}
 */
export function BrowseDirectory(pathInput) {
    return $Call.ByID(320967638, pathInput).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CleanInvalidPaths 清理无效路径并返回清理结果
 * @returns {$CancellablePromise<$models.CleanupResult>}
 */
export function CleanInvalidPaths() {
    return $Call.ByID(2552389935).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * CleanupDuplicateTools 清理重复的工具
 * @returns {$CancellablePromise<void>}
 */
export function CleanupDuplicateTools() {
    return $Call.ByID(1958404271);
}

/**
 * CleanupToolPaths 清理和修复工具路径
 * @returns {$CancellablePromise<void>}
 */
export function CleanupToolPaths() {
    return $Call.ByID(1196431871);
}

/**
 * DebugAllToolPaths 调试方法：打印所有工具的路径配置
 * @returns {$CancellablePromise<void>}
 */
export function DebugAllToolPaths() {
    return $Call.ByID(3485989415);
}

/**
 * DeleteCategory 删除分类及其下的所有工具
 * @param {string} categoryName
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCategory(categoryName) {
    return $Call.ByID(988551738, categoryName);
}

/**
 * DeleteTool 删除工具
 * @param {string} toolName
 * @param {string} categoryName
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTool(toolName, categoryName) {
    return $Call.ByID(2696011852, toolName, categoryName);
}

/**
 * DeleteToolNote 删除工具笔记 (新版本：从工具文件夹中删除)
 * @param {string} toolPath
 * @param {string} toolName
 * @returns {$CancellablePromise<void>}
 */
export function DeleteToolNote(toolPath, toolName) {
    return $Call.ByID(3189133304, toolPath, toolName);
}

/**
 * ExecuteCommand 执行工具命令（兼容旧版本）
 * @param {string} path
 * @param {string} optional
 * @param {string} value
 * @param {string} filename
 * @returns {$CancellablePromise<void>}
 */
export function ExecuteCommand(path, optional, value, filename) {
    return $Call.ByID(3010591337, path, optional, value, filename);
}

/**
 * ExecuteCommandWithCustom 执行工具命令（支持自定义命令）
 * @param {string} path
 * @param {string} optional
 * @param {string} value
 * @param {string} filename
 * @param {string} customCommand
 * @param {string} javaPath
 * @returns {$CancellablePromise<void>}
 */
export function ExecuteCommandWithCustom(path, optional, value, filename, customCommand, javaPath) {
    return $Call.ByID(859348582, path, optional, value, filename, customCommand, javaPath);
}

/**
 * ExecuteCustomCommand 执行自定义命令（兼容旧版本）
 * @param {string} path
 * @param {string} optional
 * @param {string} value
 * @param {string} filename
 * @param {string} customCommand
 * @returns {$CancellablePromise<void>}
 */
export function ExecuteCustomCommand(path, optional, value, filename, customCommand) {
    return $Call.ByID(3683189720, path, optional, value, filename, customCommand);
}

/**
 * ExecuteToolCommand 执行工具命令（新版本，支持工具对象）
 * @param {$models.Tool | null} tool
 * @param {string} customCommand
 * @returns {$CancellablePromise<void>}
 */
export function ExecuteToolCommand(tool, customCommand) {
    return $Call.ByID(4120535723, tool, customCommand);
}

/**
 * GetAllTags 获取所有标签
 * @returns {$CancellablePromise<string[]>}
 */
export function GetAllTags() {
    return $Call.ByID(2819596067).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetCategories 获取所有工具分类
 * @returns {$CancellablePromise<$models.Categories>}
 */
export function GetCategories() {
    return $Call.ByID(559270627).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetFileInfo 获取文件信息
 * @param {string} filePath
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetFileInfo(filePath) {
    return $Call.ByID(2071650585, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetFilePath 获取文件的完整路径
 * @param {string} fileName
 * @returns {$CancellablePromise<string>}
 */
export function GetFilePath(fileName) {
    return $Call.ByID(653068122, fileName);
}

/**
 * GetFileTypes 获取预定义的执行方式列表
 * @returns {$CancellablePromise<{ [_ in string]?: string }[]>}
 */
export function GetFileTypes() {
    return $Call.ByID(690605006).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetJavaConfig 获取Java配置
 * @returns {$CancellablePromise<$models.JavaConfig | null>}
 */
export function GetJavaConfig() {
    return $Call.ByID(2331348845).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetNewToolsFromScanned 获取真正的新工具（过滤掉已存在的）
 * @param {$models.ScannedTool[]} tools
 * @returns {$CancellablePromise<$models.ScannedTool[]>}
 */
export function GetNewToolsFromScanned(tools) {
    return $Call.ByID(259450018, tools).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetToolAbsolutePath 获取工具的绝对路径
 * @param {string} toolPath
 * @param {string} fileName
 * @returns {$CancellablePromise<string>}
 */
export function GetToolAbsolutePath(toolPath, fileName) {
    return $Call.ByID(2362181999, toolPath, fileName);
}

/**
 * GetToolDirectory 获取工具目录的文件列表（用于编辑工具时选择文件）
 * @param {string} toolPath
 * @returns {$CancellablePromise<$models.FileInfo[]>}
 */
export function GetToolDirectory(toolPath) {
    return $Call.ByID(742418308, toolPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetToolNote 获取工具笔记 (新版本：从工具文件夹中读取)
 * @param {string} toolPath
 * @param {string} toolName
 * @returns {$CancellablePromise<string>}
 */
export function GetToolNote(toolPath, toolName) {
    return $Call.ByID(4270888193, toolPath, toolName);
}

/**
 * GetToolTypes 获取支持的工具类型
 * @returns {$CancellablePromise<string[]>}
 */
export function GetToolTypes() {
    return $Call.ByID(2316340630).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * OpenDirectoryDialog 打开目录选择对话框
 * @returns {$CancellablePromise<string>}
 */
export function OpenDirectoryDialog() {
    return $Call.ByID(1188724780);
}

/**
 * OpenFileDialog 打开文件选择对话框
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function OpenFileDialog() {
    return $Call.ByID(4196526771).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * OpenGitHubPage 在默认浏览器中打开GitHub页面 (macOS专用)
 * @returns {$CancellablePromise<void>}
 */
export function OpenGitHubPage() {
    return $Call.ByID(1286261325);
}

/**
 * OpenToolDirectory 打开工具所在目录
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenToolDirectory(path) {
    return $Call.ByID(4116350290, path);
}

/**
 * RepairConfigFile 修复损坏的配置文件
 * @returns {$CancellablePromise<void>}
 */
export function RepairConfigFile() {
    return $Call.ByID(4262117628);
}

/**
 * SaveJavaConfig 保存Java配置
 * @param {$models.JavaConfig} javaConfig
 * @returns {$CancellablePromise<void>}
 */
export function SaveJavaConfig(javaConfig) {
    return $Call.ByID(1276912958, javaConfig);
}

/**
 * SaveToolNote 保存工具笔记 (新版本：保存到工具文件夹中)
 * @param {string} toolPath
 * @param {string} toolName
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SaveToolNote(toolPath, toolName, content) {
    return $Call.ByID(414356438, toolPath, toolName, content);
}

/**
 * ScanCustomDirectoryForTools 扫描自定义目录寻找工具
 * @param {string} customPath
 * @returns {$CancellablePromise<$models.ScannedTool[]>}
 */
export function ScanCustomDirectoryForTools(customPath) {
    return $Call.ByID(2359958488, customPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * ScanResourcesForTools 扫描resources文件夹寻找工具
 * @returns {$CancellablePromise<$models.ScannedTool[]>}
 */
export function ScanResourcesForTools() {
    return $Call.ByID(3738826843).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * ScanToolsInCustomPath 扫描自定义路径下的工具（使用绝对路径）
 * 支持两种目录结构：
 * 1. 分类式：customPath/category1/tool1, customPath/category2/tool2
 * 2. 平铺式：customPath/tool1, customPath/tool2 (统一归类为"自定义工具")
 * @param {string} scanPath
 * @returns {$CancellablePromise<$models.ScannedTool[]>}
 */
export function ScanToolsInCustomPath(scanPath) {
    return $Call.ByID(74566772, scanPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * ScanToolsInPath 扫描指定路径下的工具
 * resources文件夹下的每个目录是分类文件夹，每个分类下的子目录是工具文件夹
 * @param {string} scanPath
 * @returns {$CancellablePromise<$models.ScannedTool[]>}
 */
export function ScanToolsInPath(scanPath) {
    return $Call.ByID(3902763887, scanPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * SearchTools 搜索工具（支持标签搜索）
 * @param {string} query
 * @returns {$CancellablePromise<$models.Tool[]>}
 */
export function SearchTools(query) {
    return $Call.ByID(774999472, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * Select 打开文件/目录选择对话框（限制在 App 包内 resources 目录下）
 * @param {boolean} selectFolder
 * @returns {$CancellablePromise<string>}
 */
export function Select(selectFolder) {
    return $Call.ByID(149583269, selectFolder);
}

/**
 * SelectDirectory 选择目录（用于前端文件夹选择器）
 * @returns {$CancellablePromise<string>}
 */
export function SelectDirectory() {
    return $Call.ByID(1735672136);
}

/**
 * SelectFile 选择文件
 * @returns {$CancellablePromise<string>}
 */
export function SelectFile() {
    return $Call.ByID(2427571203);
}

/**
 * SelectJavaPath 选择Java路径（选择具体的Java可执行文件）
 * @returns {$CancellablePromise<string>}
 */
export function SelectJavaPath() {
    return $Call.ByID(3105890934);
}

/**
 * UpdateCategoriesOrder 更新分类顺序
 * @param {$models.Category[]} orderedCategories
 * @returns {$CancellablePromise<void>}
 */
export function UpdateCategoriesOrder(orderedCategories) {
    return $Call.ByID(1314594168, orderedCategories);
}

/**
 * UpdateCategoryIcon 更新分类图标
 * @param {string} categoryName
 * @param {string} icon
 * @returns {$CancellablePromise<void>}
 */
export function UpdateCategoryIcon(categoryName, icon) {
    return $Call.ByID(1745597621, categoryName, icon);
}

/**
 * UpdateCategoryName 更新分类名称
 * @param {string} oldName
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function UpdateCategoryName(oldName, newName) {
    return $Call.ByID(1433504655, oldName, newName);
}

/**
 * UpdateCategoryTools 批量更新分类下工具顺序
 * @param {string} categoryName
 * @param {$models.Tool[]} tools
 * @returns {$CancellablePromise<void>}
 */
export function UpdateCategoryTools(categoryName, tools) {
    return $Call.ByID(158904039, categoryName, tools);
}

/**
 * UpdateTool 更新工具信息
 * @param {string} originalName
 * @param {string} categoryName
 * @param {$models.Tool} tool
 * @returns {$CancellablePromise<void>}
 */
export function UpdateTool(originalName, categoryName, tool) {
    return $Call.ByID(1267963494, originalName, categoryName, tool);
}

/**
 * UpdateToolDescription 更新工具描述
 * @param {string} toolName
 * @param {string} categoryName
 * @param {string} description
 * @returns {$CancellablePromise<void>}
 */
export function UpdateToolDescription(toolName, categoryName, description) {
    return $Call.ByID(2686528344, toolName, categoryName, description);
}

// Private type creation functions
const $$createType0 = $models.FileInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.CleanupResult.createFrom;
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $models.Categories.createFrom;
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.JavaConfig.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $models.ScannedTool.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $models.Tool.createFrom;
const $$createType12 = $Create.Array($$createType11);
