// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Categories 分类列表结构体
 */
export class Categories {
    /**
     * Creates a new Categories instance.
     * @param {Partial<Categories>} [$$source = {}] - The source object to create the Categories.
     */
    constructor($$source = {}) {
        if (!("categories" in $$source)) {
            /**
             * @member
             * @type {Category[]}
             */
            this["categories"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Categories instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Categories}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("categories" in $$parsedSource) {
            $$parsedSource["categories"] = $$createField0_0($$parsedSource["categories"]);
        }
        return new Categories(/** @type {Partial<Categories>} */($$parsedSource));
    }
}

/**
 * Category 分类结构体
 */
export class Category {
    /**
     * Creates a new Category instance.
     * @param {Partial<Category>} [$$source = {}] - The source object to create the Category.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * 分类图标
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("tools" in $$source)) {
            /**
             * @member
             * @type {Tool[]}
             */
            this["tools"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Category instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Category}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField2_0($$parsedSource["tools"]);
        }
        return new Category(/** @type {Partial<Category>} */($$parsedSource));
    }
}

/**
 * CleanupResult 清理结果统计
 */
export class CleanupResult {
    /**
     * Creates a new CleanupResult instance.
     * @param {Partial<CleanupResult>} [$$source = {}] - The source object to create the CleanupResult.
     */
    constructor($$source = {}) {
        if (!("invalidToolsCount" in $$source)) {
            /**
             * 清理的无效工具数量
             * @member
             * @type {number}
             */
            this["invalidToolsCount"] = 0;
        }
        if (!("invalidCategoriesCount" in $$source)) {
            /**
             * 清理的无效分类数量
             * @member
             * @type {number}
             */
            this["invalidCategoriesCount"] = 0;
        }
        if (!("cleanedNotes" in $$source)) {
            /**
             * 清理的笔记文件数量
             * @member
             * @type {number}
             */
            this["cleanedNotes"] = 0;
        }
        if (!("migratedNotes" in $$source)) {
            /**
             * 迁移的笔记文件数量
             * @member
             * @type {number}
             */
            this["migratedNotes"] = 0;
        }
        if (!("invalidToolNames" in $$source)) {
            /**
             * 被清理的工具名称列表
             * @member
             * @type {string[]}
             */
            this["invalidToolNames"] = [];
        }
        if (!("migratedToolNames" in $$source)) {
            /**
             * 被迁移的工具名称列表
             * @member
             * @type {string[]}
             */
            this["migratedToolNames"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CleanupResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CleanupResult}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType4;
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("invalidToolNames" in $$parsedSource) {
            $$parsedSource["invalidToolNames"] = $$createField4_0($$parsedSource["invalidToolNames"]);
        }
        if ("migratedToolNames" in $$parsedSource) {
            $$parsedSource["migratedToolNames"] = $$createField5_0($$parsedSource["migratedToolNames"]);
        }
        return new CleanupResult(/** @type {Partial<CleanupResult>} */($$parsedSource));
    }
}

/**
 * FileInfo 文件信息结构体
 */
export class FileInfo {
    /**
     * Creates a new FileInfo instance.
     * @param {Partial<FileInfo>} [$$source = {}] - The source object to create the FileInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("modTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modTime"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("extension" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["extension"] = "";
        }
        if (!("isExecutable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isExecutable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileInfo(/** @type {Partial<FileInfo>} */($$parsedSource));
    }
}

/**
 * JavaConfig Java配置结构体
 */
export class JavaConfig {
    /**
     * Creates a new JavaConfig instance.
     * @param {Partial<JavaConfig>} [$$source = {}] - The source object to create the JavaConfig.
     */
    constructor($$source = {}) {
        if (!("Java8" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Java8"] = "";
        }
        if (!("Java11" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Java11"] = "";
        }
        if (!("Java17" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Java17"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JavaConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {JavaConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JavaConfig(/** @type {Partial<JavaConfig>} */($$parsedSource));
    }
}

/**
 * ScannedTool 扫描到的工具信息
 */
export class ScannedTool {
    /**
     * Creates a new ScannedTool instance.
     * @param {Partial<ScannedTool>} [$$source = {}] - The source object to create the ScannedTool.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * 工具相对路径
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * 分类名称
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("possibleFiles" in $$source)) {
            /**
             * 可能的可执行文件列表
             * @member
             * @type {string[]}
             */
            this["possibleFiles"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScannedTool instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScannedTool}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("possibleFiles" in $$parsedSource) {
            $$parsedSource["possibleFiles"] = $$createField2_0($$parsedSource["possibleFiles"]);
        }
        return new ScannedTool(/** @type {Partial<ScannedTool>} */($$parsedSource));
    }
}

/**
 * Tool 工具结构体
 */
export class Tool {
    /**
     * Creates a new Tool instance.
     * @param {Partial<Tool>} [$$source = {}] - The source object to create the Tool.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * 工具唯一ID: {工具名称}-{YYYYMMDD}
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * 工具名称
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * 工具路径
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("fileName" in $$source)) {
            /**
             * 文件名
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * 执行类型
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * 命令
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (!("optional" in $$source)) {
            /**
             * 可选参数
             * @member
             * @type {string}
             */
            this["optional"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * 描述
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * 标签列表
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("sourceUrl" in $$source)) {
            /**
             * 来源URL
             * @member
             * @type {string}
             */
            this["sourceUrl"] = "";
        }
        if (!("iconPath" in $$source)) {
            /**
             * 自定义图标路径
             * @member
             * @type {string}
             */
            this["iconPath"] = "";
        }
        if (!("openCount" in $$source)) {
            /**
             * 打开次数
             * @member
             * @type {number}
             */
            this["openCount"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * 创建时间
             * @member
             * @type {string}
             */
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("lastUsedAt" in $$source)) {
            /**
             * 最后使用时间
             * @member
             * @type {string}
             */
            this["lastUsedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tool instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Tool}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField8_0($$parsedSource["tags"]);
        }
        return new Tool(/** @type {Partial<Tool>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Category.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Tool.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
